// <auto-generated />
using System;
using BootManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BootManager.Infrastructure.Migrations
{
    [DbContext(typeof(BootManagerDbContext))]
    [Migration("20260620120948_AddInventoryEntities")]
    partial class AddInventoryEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BootManager.Core.Entities.BatteryMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StateOfCharge")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Voltage")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("BatteryMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.DepthMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DepthMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("DepthMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.FluidLevelMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CapacityLiters")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<byte>("FluidInstance")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FluidType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GatewaySentence")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLevelInvalid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LevelPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Pgn")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("RawFluidType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<byte?>("SourceAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FluidType");

                    b.HasIndex("RecordedAtUtc");

                    b.HasIndex("FluidType", "FluidInstance");

                    b.ToTable("FluidLevelMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.HeadingMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HeadingDegrees")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("HeadingMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CredentialVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedProfilePayload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("EncryptionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PasswordChangeRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinSalt")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryCodeHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryCodeSalt")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("LocalUsers", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.LogbookAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogbookEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogbookEntryId");

                    b.ToTable("LogbookAttachments", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.LogbookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AverageSogKnots")
                        .HasPrecision(7, 3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BaroPressure")
                        .HasPrecision(7, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Course")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GpsStatus")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("LogValue")
                        .HasPrecision(10, 3)
                        .HasColumnType("TEXT");

                    b.Property<int>("LogbookTripId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindDescription")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LogbookTripId", "EntryTimeUtc");

                    b.ToTable("LogbookEntries", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.LogbookTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivalUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Crew")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeparturePort")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationPort")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EngineHoursEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EngineHoursStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fuel")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("LogIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(60);

                    b.Property<decimal?>("LoggedMiles")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LogstandEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LogstandStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TotalSailingHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartureUtc");

                    b.ToTable("LogbookTrips", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.MotionMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CourseOverGroundDegrees")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpeedOverGround")
                        .HasPrecision(8, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeedUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("MotionMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.NetworkMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHex")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("NetworkMessages", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.OperationalSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AlternativeListenPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CaptureLoggingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultSampleIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IngestProcessingEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListenAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ListenPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogbookAttachmentsDirectory")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawStorageMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperationalSettings", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.PositionMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("PositionMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DefaultUnitId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultUnitId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.ProductCategoryMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("ProductId", "IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("ProductCategoryMappings", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.ProductCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedValue")
                        .IsUnique();

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductCodes", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.SpeedThroughWaterMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpeedKnots")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpeedMetersPerSecond")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<byte>("SpeedWaterReferenceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("SpeedThroughWaterMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.StorageArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("StorageAreas", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("QrToken")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StorageAreaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("QrToken")
                        .IsUnique()
                        .HasFilter("\"QrToken\" IS NOT NULL");

                    b.HasIndex("StorageAreaId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("StorageLocations", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Units", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.VesselProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CallSign")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentEngineHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CurrentLogstand")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("HomePort")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mmsi")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("VesselProfiles", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.WaterTemperatureMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TemperatureCelsius")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<byte>("TemperatureInstance")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TemperatureKelvin")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("WaterTemperatureMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.WindMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeedUnit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WindAngleDegrees")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WindSpeed")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.ToTable("WindMeasurements", (string)null);
                });

            modelBuilder.Entity("BootManager.Core.Entities.LogbookAttachment", b =>
                {
                    b.HasOne("BootManager.Core.Entities.LogbookEntry", "Entry")
                        .WithMany("Attachments")
                        .HasForeignKey("LogbookEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("BootManager.Core.Entities.LogbookEntry", b =>
                {
                    b.HasOne("BootManager.Core.Entities.LogbookTrip", "Trip")
                        .WithMany("Entries")
                        .HasForeignKey("LogbookTripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BootManager.Core.Entities.Product", b =>
                {
                    b.HasOne("BootManager.Core.Entities.Unit", "DefaultUnit")
                        .WithMany("Products")
                        .HasForeignKey("DefaultUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultUnit");
                });

            modelBuilder.Entity("BootManager.Core.Entities.ProductCategoryMapping", b =>
                {
                    b.HasOne("BootManager.Core.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductMappings")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BootManager.Core.Entities.Product", "Product")
                        .WithMany("CategoryMappings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("BootManager.Core.Entities.ProductCode", b =>
                {
                    b.HasOne("BootManager.Core.Entities.Product", "Product")
                        .WithOne("Code")
                        .HasForeignKey("BootManager.Core.Entities.ProductCode", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BootManager.Core.Entities.StorageLocation", b =>
                {
                    b.HasOne("BootManager.Core.Entities.StorageArea", "StorageArea")
                        .WithMany("Locations")
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageArea");
                });

            modelBuilder.Entity("BootManager.Core.Entities.LogbookEntry", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("BootManager.Core.Entities.LogbookTrip", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BootManager.Core.Entities.Product", b =>
                {
                    b.Navigation("CategoryMappings");

                    b.Navigation("Code");
                });

            modelBuilder.Entity("BootManager.Core.Entities.ProductCategory", b =>
                {
                    b.Navigation("ProductMappings");
                });

            modelBuilder.Entity("BootManager.Core.Entities.StorageArea", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("BootManager.Core.Entities.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
