// <auto-generated />
using System;
using BootManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BootManager.Infrastructure.Migrations
{
    [DbContext(typeof(BootManagerDbContext))]
    partial class BootManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BootManager.Core.Entities.OwnerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedProfilePayload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("EncryptionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryCodeHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecoveryCodeSalt")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("OwnerProfiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
